### ISSUE TITLE
need at least one array to concatenate

### ISSUE THREAD

**Issue by lilydablue** [gist-ailab/teaching-where-to-look#14]
hello!
Thank you for adding the Identification code.
I wanted to test the code with the checkpoint.
I used the script below:
!python /content/teaching-where-to-look/test_tinyface.py --checkpoint_path /content/base_24/last_net.ckpt --batch_size 128 --tinyface_dir /content/tinyface --save_dir /content/test_result --gpus 0

and I have this Error:

probe images : 0
gallery images : 0
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/content/teaching-where-to-look/test_tinyface.py", line 157, in <module>
    probe_features = infer(model, probe_loader, use_flip_test=args.use_flip_test)
  File "/content/teaching-where-to-look/test_tinyface.py", line 80, in infer
    features = np.concatenate(features, axis=0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

Can you guide me with that?

**Comment by Farisalem** [comment]
I have the exact same error and this is really important to me.
Thank you in advance for your consideration.

**Comment by tjdhg456** [comment]
Hello.

In your code, the number of probe and gallery images are zero.
It because tinyface dir is not set exactly.

--------------------------------------------------------------------------------------------------------------------------
Download the pre-processed [TinyFace dataset](https://github.com/mk-minchul/AdaFace/tree/master/validation_lq). After unzip, the directory structure can be defined as follows:

- aligned_pad_0.1_pad_high/  # TINYFACE_DIR
    - Probe/
    - Train/
    - Gallery_Match/
    - Gallery_Disctractor/

**Comment by lilydablue** [comment]
thank you for your kindness.
now my probe and gallery are ready like this:
probe images : 3728
gallery images : 157871

now I have this error.
RuntimeError: stack expects each tensor to be equal size, but got [3, 32, 29] at entry 0 and [3, 32, 32] at entry 1
